# /.github/workflows/publish.yaml
# Build and publish the library when a new tag is pushed

name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x, 17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # This is required to ensure the linter does not fail on Windows
      - name: Disable `git autocrlf`
        run: |
          git config --global core.autocrlf false
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build, lint and test the library
        run: npm test

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
