# /.github/workflows/test.yaml
# Build, lint and test the library

name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x, 17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # This is required to ensure the linter does not fail on Windows
      - name: Disable `git autocrlf`
        run: |
          git config --global core.autocrlf false
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build, lint and test the library
        run: npm test
